### ISSUE TITLE
How to expose full validation error in response?

### ISSUE THREAD

**Issue by oldo** [JakeFenley/koa-zod-router#10]
Love the library! Thank you!

I was wondering, when a validation error occurs I'm just getting back a 400 response with body `VALIDATION_ERROR`. Is there any way to configure the router to respond with all `ZodError` issues?

**Comment by JakeFenley** [comment]
Awesome, glad to hear you are loving it!  This is indeed configurable, you can use the exposeRequestErrors and exposeResponseErrors flags. [docs](https://github.com/JakeFenley/koa-zod-router/blob/main/docs/API.md)

**Comment by oldo** [comment]
Thanks for the fast response!

**Comment by JakeFenley** [comment]
Np! Feel free to leave any feedback or ideas you may have in the [discussions](https://github.com/JakeFenley/koa-zod-router/discussions)
