### ISSUE TITLE
Extending the router context?

### ISSUE THREAD

**Issue by denizdogan** [JakeFenley/koa-zod-router#25]
Is there any way to extend the router context? I noticed that `RouterState` is generic, but the context is hardcoded to `DefaultContext`.

**Comment by denizdogan** [comment]
Hmm, I guess I should get my eyes examined.

**Comment by tommy-mitchell** [comment]
@denizdogan what was the solution? I can't seem to figure it out either.

**Comment by denizdogan** [comment]
@tommy-mitchell I honestly don't remember, but these lines have `Context = DefaultContext` which could be a pointer in the right direction: https://github.com/JakeFenley/koa-zod-router/blob/e66a5d4f7bd1ca583f819843fe7f73d0d8b009f3/src/zod-router.ts#L77-L90

**Comment by JakeFenley** [comment]
Hi @tommy-mitchell what exactly are you trying to do?

**Comment by tommy-mitchell** [comment]
@JakeFenley I'm using https://github.com/unix/koa-custom-response, which adds a few methods onto `ctx`. I'd like to be able to use `createRouteSpec` and `router.register` with this custom context.

**Comment by tommy-mitchell** [comment]
@JakeFenley cheers, that works perfectly!

**Comment by JakeFenley** [comment]
glad to hear it @tommy-mitchell , just fyi I've released 2.0.0 for when you next update your dependencies, cheers!
