### ISSUE TITLE
Customize error display

### ISSUE THREAD

**Issue by lbesson-della** [JakeFenley/koa-zod-router#26]
It seems that we cannot customize error display (except via the exposeRequestErrors or exposeResponseErrors options).
I'd like to be able to customize the error format (for example in order to give more user friendly messages)

Is it something that is possible, do you intend to implement it, or would you be open for a PR in that sense?

**Comment by JakeFenley** [comment]
Hi @lbesson-della, thanks for the input.

I'm currently working on a new release where I'm formatting the errors a bit better. But I'm open to any suggestions you have.

What exactly did you have in mind as far as the feature you are proposing?

**Comment by JakeFenley** [comment]
it will be fairly similar, except rather than than pass the handler as an option, you'll be able to add your error-handler as a middleware to the router before your actual request handlers. or make it route specific if you want to do it that way too. I might actually have it released today if i can get it properly tested and working hopefully 😄

**Comment by JakeFenley** [comment]
hi @lbesson-della i've gone ahead and released 1.2.0. you can find details of how you can achieve custom error handling [here](https://github.com/JakeFenley/koa-zod-router#custom-validation-error-handling). 

Hope you find it to be useful, and appreciate your feedback so far. Let me know of any additional feedback you may have! Thanks!

**Comment by lbesson-della** [comment]
hello,

I haven't time to look at it yet, but will definitely do

**Comment by lbesson-della** [comment]
Hello,

I've been giving it a try, but I think I got a bit lost with the middleware order when it's mixed with routers.

I've tryed different versions of the code below, but the validationErrorMiddleware is always called before the actual validation of the input

What I ultimately would like to achieve is that when I get a request, I first go the the auth middleware to check if the request is valide (for every endpoint), then the endpoint being validated with it's specific validator instance, catch all validation errors with the validationErrorMiddleware, and if everything is fine, finally pass it to my endpoint handler

```ts
export const router = zodRouter({
  zodRouter: { enableMultipart: true, continueOnError: true }
});

router.use(myAuthMiddleware); // middleware to validate jwt for each request linked to the router

const errorSpecFactory = routerSpecFactory();
const validationErrorMiddleware = errorSpecFactory.createUseSpec({
  handler: async (ctx, next) => {
    if (ctx['invalid']?.error) {
      ctx.throw(400, 'customerrror');
      return;
    } else {
      await next();
    }
  }
});
router.use(validationErrorMiddleware);

router.get(
  "/object/:id",
  async ctx => {
    ctx.body = 'OK';
  },
  validate: {
    params: {
      id: z.string().uuid()
    }
  }
);
```

**Comment by JakeFenley** [comment]
Looks like I made a mistake of not testing it out with the use method, and tested with regular route handlers instead 🤦 . Sorry about this, I'm going to work towards getting a fix soon. Thanks for input

**Comment by JakeFenley** [comment]
hi @lbesson-della I'm adding this to 2.0.0. you can try out the beta by installing `koa-zod-router@beta`

```
import { ValidationErrorHandler } from 'koa-zod-router';

const validationErrorHandler: ValidationErrorHandler = async (ctx, next) => {
  if (ctx.invalid.error) {
    ctx.status = 400;
    ctx.body = 'hello';
  } else {
    await next();
  }

  return;
};

const router = zodRouter<UserState>({
  zodRouter: { exposeRequestErrors: true, exposeResponseErrors: true, validationErrorHandler },
});
```

**Comment by lbesson-della** [comment]
Thanks.
Will have a look asap

**Comment by lbesson-della** [comment]
Thanks @JakeFenley, this seems to perfectly fit my needs.
