### ISSUE TITLE
Decouple validation

### ISSUE THREAD

**Issue by IlyaSemenov** [JakeFenley/koa-zod-router#34]
I want to add zod validation to my existing router/routes which I'm happy with. Is there a recipe for using the validation part only, or is your library monolithic and only works as a full blown router?

I am thinking of something like:

```ts
myrouter.post("/foo", ctx => {
  // my existing router logic
})
```

enhanced as:

```ts
myrouter.post(
  "/foo",
  validate(
    {
      body: z.object(...),
    },
    ctx => {
      // my existing router logic, with ctx.body validated and typed
    },
  ),
)
```

**Comment by JakeFenley** [comment]
Hello, there is no decoupled validation export. The validation is only apart of the router's middleware

**Comment by IlyaSemenov** [comment]
No, I can't really. Take this code:

```ts
import Router, { RouterContext } from '@koa/router'

export const router = new Router()
```

If I replace `@koa/router` with `koa-zod-router` this gives a bunch of errors immediately:

```ts
import Router, { RouterContext } from 'koa-zod-router'
// Module '"koa-zod-router"' has no exported member 'RouterContext'. Did you mean to use 'import RouterContext from "koa-zod-router"' instead?

export const router = new Router()
// 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.
```

Of course I understand I can probably rewrite the entire code base relatively easily, but why bother for a few hundreds of routes? Routing and validating are unrelated concepts in my thinking.

Anyhow, thank you for the response. I will probably come up with my own implementation then.
