### ISSUE TITLE
Handlers/controllers in separate files

### ISSUE THREAD

**Issue by krosenk729** [JakeFenley/koa-zod-router#37]
We're using typescript with `strict: true`, so there cannot be any implicit any types. We want to use `koa-zod-router` but putting the controller in-line in the route definition is not going to scale. How can we get the `ctx` type in a handler when it's not an inline function?

Using the sample code from the readme with small updates:
`index.ts`
```
import Koa from "koa";
import zodRouter from "koa-zod-router";
import { z } from "zod";
import { controller } from "./controller";

const app = new Koa();

const router = zodRouter();

router.register({
  name: "example",
  method: "post",
  path: "/post/:id",
  handler: controller, // ⭐️ not inlined
  validate: {
    params: z.object({ id: z.coerce.number() }),
    body: z.object({ foo: z.number() }),
    response: z.object({ hello: z.string() }),
  },
});

app.use(router.routes());

app.listen(3000, () => {
  console.log("app listening on http://localhost:3000");
});

```

`controllers.ts`
```
// 🚨 gives a typescript error of Parameter 'ctx' implicitly has an 'any' type
export const controller = async (ctx, next) => {
  const { foo } = ctx.request.body;
  ctx.body = { hello: "world" };

  await next();
};
```

**Comment by JakeFenley** [comment]
Hello,

If you want to import/export routes currently the only way to do it is shown here in this [example](https://github.com/JakeFenley/koa-zod-router#importingexporting-routes)

There is currently no way to infer ctx in the way you are trying to export your route as router.register is mapping generic types under the hood.
