### ISSUE TITLE
ctx.invalid.{body,headers,params...} is an object despite the type being an array of ZodError

### ISSUE THREAD

**Issue by ADRFranklin** [JakeFenley/koa-zod-router#39]
Hi,

Just started using this library and came across a problem where trying to restructure the errors provided by `ctx.invalid` inside a custom `validationErrorHandler` function, that is that the type shows the fields to be `ZodError[]` but the actual type at runtime is an object and not an array. 

I'm in no way a typescript expert so please let me know if this is something I am doing wrong. Other then this issue, I am really liking the library.

**Comment by JakeFenley** [comment]
Hi @ADRFranklin could you provide a code sample please?

**Comment by ADRFranklin** [comment]
Yes, sure thing.

```ts
const apiRouter = zodRouter<HttpState>({
      zodRouter: {
        exposeRequestErrors: env.loglevel === 'debug',
        exposeResponseErrors: env.loglevel === 'debug',
        validationErrorHandler: async (ctx, next) => {
          if (ctx.invalid?.error) {
            const { body, headers, params, files, query } = ctx.invalid;
            console.log(typeof body);
          }
          await next();
        }
      }
    });
 ```
 
 The output given for that is just `object`

**Comment by ADRFranklin** [comment]
@JakeFenley Sorry I just saw your message was edited, I came straight from the email haha. Thanks I will upgrade.
