### ISSUE TITLE
How to apply middleware from a specFactory on a single route?

### ISSUE THREAD

**Issue by ADRFranklin** [JakeFenley/koa-zod-router#41]
Hello,

I am trying to apply middleware to some routes, unfortunately because the middleware makes use of `createUseSpec` it is not compatible with the `.use` on a route register as such

```
 userRouter.register(getAllUsers).use(isAdmin);
 ```
 
 I didn't think it made sense for one route out of 11 to make a separate router to apply the middleware to just to apply to that one route and since the `createRouteSpec` doesn't seem to have a way to pass middleware there either, I wasn't sure what the correct or expected way of doing it was?

**Comment by JakeFenley** [comment]
There isn't any integration for types with the zod validation object at the moment, but you can use the Middleware type from koa as a workaround.

for example:
`
import {Middleware} from 'koa'
const middleware: Middleware = async (ctx, next) => {//...}

router.get(
  '/',
  [
    middleware,
    //... route handler
  ],
  {
    //...validation body
  }
)`

if using router.register or createRouteSpec, you would just turn `handler` into an array

**Comment by ADRFranklin** [comment]
Oh, I wasn't aware you could pass an array of middleware to the route itself, thanks this is much better.

**Comment by JakeFenley** [comment]
no problem! yeah at some point i'd like to deprecate createRouteSpec and createUseSpec and come up with a better way to export handlers/middlewares with zod and type inference. Those 2 functions were sort of an after thought when I was intially releasing the library.
