### ISSUE TITLE
Q: Is it possible to add avlidation on filetype/mimetype by file upload?

### ISSUE THREAD

**Issue by dennisfrijlink** [JakeFenley/koa-zod-router#44]
For example

```
router.post({
    path: "/",
    handler: async (ctx, next) => {
        const { upload } = ctx?.request?.files;
        ....
        ....
        await next();
    },
    validate: {
        files: z.object({
            upload: zFile(), // only allow 'image/jpeg'
        }),
    },
});
```

**Comment by JakeFenley** [comment]
Hello,

No at the moment it is not that granular, this only validates that a file was sent in the request. Although I'm sure it'd be fairly straightforward to implement something like this, if you'd like to open a PR

**Comment by dennisfrijlink** [comment]
Hi @JakeFenley,

Thanks for your answer! Maybe you can implement it because I'm not yet experienced with koa-zod-router.
