### ISSUE TITLE
Move types to dev dependencies?

### ISSUE THREAD

**Issue by cloudrac3r** [JakeFenley/koa-zod-router#45]
Currently, package.json has these dependencies:

```
    "@types/formidable": "^2.0.6",
    "@types/koa-bodyparser": "^4.3.11",
    "@types/koa__router": "^12.0.2",
```

Could these be moved to dev dependencies? This would make the npm install size smaller. The koa-zod-router tests pass after making this change. But I don't know if it would break other projects that use koa-zod-router.

**Comment by JakeFenley** [comment]
Hey, thanks for looking into this! 

I think this was intentional but I can't really remember the reason why. I'm happy to accept a PR for this and test it in a beta version.
