### ISSUE TITLE
Exported variable ... has or is using name 'ZodContext' from external module

### ISSUE THREAD

**Issue by eigBabcock** [JakeFenley/koa-zod-router#9]
Tried using the example for pulling in routes from a different file but get an error `Exported variable 'routeMe' has or is using name 'ZodContext' from external module ".../node_modules/.pnpm/koa-zod-router@1.0.3_6qvceonjeialq36lgrl7dj2ju4/node_modules/koa-zod-router/dist/index" but cannot be named.`

Sample code:
```
// routeMe.ts
export const routeMe= createRouteSpec({
  name: 'route-me',
  method: 'get',
  path: '/route-me',
  handler: handleRouteMe,
  validate: {
    body: RouteMeRequestBodySchema,
    response: RouteMeResponseSchema,
  },
})
```

```
// index.ts
router.register(routeMe)
```

When I use `createRouteSpec` in my `index.ts` file everything works, but I would much rather have my routes defined elsewhere.

Package Manager: `pnpm`
Using version `1.0.3`
Project is ESM
All peer dependencies met

**Comment by JakeFenley** [comment]
Hmm I think could be due to having "declaration": true set in tsconfig.json, at least thats how I eventually triggered the error. I think maybe disabling it could get it to go away. I'll have to look into why this is causing issues though

**Comment by JakeFenley** [comment]
Hi @eigBabcock can you do me a favor and `pnpm install koa-zod-router@beta` for me please? I think this should fix your issue 🤞
